export const flightsData = [
    {
      id: '1',
      flightNumber: 'LH123',
      aircraft: 'Airbus A320',
      from: 'BER',
      to: 'JFK',
      departureDate: '2024-09-15',
      departureTime: '06:00 PM',
      arrivalDate: '2024-09-15',
      arrivalTime: '10:00 PM',
      price: 500,
      airline: 'Lufthansa',
      flightDuration: '8h',
    },
    {
      id: '2',
      flightNumber: 'FR456',
      aircraft: 'Boeing 737',
      from: 'BER',
      to: 'BUD',
      departureDate: '2024-09-16',
      departureTime: '10:00 AM',
      arrivalDate: '2024-09-16',
      arrivalTime: '12:00 PM',
      price: 150,
      airline: 'Ryanair',
      flightDuration: '2h',
    },
    {
      id: '3',
      flightNumber: 'EZ789',
      aircraft: 'Airbus A319',
      from: 'BER',
      to: 'CPH',
      departureDate: '2024-09-17',
      departureTime: '02:00 PM',
      arrivalDate: '2024-09-17',
      arrivalTime: '03:00 PM',
      price: 120,
      airline: 'EasyJet',
      flightDuration: '1h',
    },
    {
      id: '4',
      flightNumber: 'AF321',
      aircraft: 'Boeing 787',
      from: 'BER',
      to: 'GIG',
      departureDate: '2024-09-18',
      departureTime: '10:00 PM',
      arrivalDate: '2024-09-19',
      arrivalTime: '06:00 AM',
      price: 700,
      airline: 'Air France',
      flightDuration: '12h',
    },
    {
      id: '5',
      flightNumber: 'TK654',
      aircraft: 'Airbus A321',
      from: 'BER',
      to: 'IST',
      departureDate: '2024-09-19',
      departureTime: '09:00 AM',
      arrivalDate: '2024-09-19',
      arrivalTime: '12:00 PM',
      price: 200,
      airline: 'Turkish Airlines',
      flightDuration: '3h',
    },
    {
      id: '6',
      flightNumber: 'DL789',
      aircraft: 'Boeing 767',
      from: 'JFK',
      to: 'BER',
      departureDate: '2024-09-20',
      departureTime: '05:00 PM',
      arrivalDate: '2024-09-21',
      arrivalTime: '07:00 AM',
      price: 550,
      airline: 'Delta',
      flightDuration: '8h',
    },
    {
      id: '7',
      flightNumber: 'W6A123',
      aircraft: 'Airbus A320',
      from: 'BUD',
      to: 'BER',
      departureDate: '2024-09-21',
      departureTime: '11:00 AM',
      arrivalDate: '2024-09-21',
      arrivalTime: '01:00 PM',
      price: 160,
      airline: 'Wizz Air',
      flightDuration: '2h',
    },
    {
      id: '8',
      flightNumber: 'SAS456',
      aircraft: 'Airbus A321',
      from: 'CPH',
      to: 'BER',
      departureDate: '2024-09-22',
      departureTime: '08:00 AM',
      arrivalDate: '2024-09-22',
      arrivalTime: '09:00 AM',
      price: 130,
      airline: 'SAS',
      flightDuration: '1h',
    },
    {
      id: '9',
      flightNumber: 'LA789',
      aircraft: 'Boeing 787',
      from: 'GIG',
      to: 'BER',
      departureDate: '2024-09-23',
      departureTime: '08:00 PM',
      arrivalDate: '2024-09-24',
      arrivalTime: '12:00 PM',
      price: 720,
      airline: 'LATAM',
      flightDuration: '12h',
    },
    {
      id: '10',
      flightNumber: 'PC321',
      aircraft: 'Airbus A320',
      from: 'IST',
      to: 'BER',
      departureDate: '2024-09-24',
      departureTime: '02:00 PM',
      arrivalDate: '2024-09-24',
      arrivalTime: '05:00 PM',
      price: 210,
      airline: 'Pegasus',
      flightDuration: '3h',
    },
  ];
  
  export const cities = [
    {label: 'All', value: 'all'},
    {label: 'New York', value: 'JFK'},
    {label: 'Budapest', value: 'BUD'},
    {label: 'Copenhagen', value: 'CPH'},
    {label: 'Rio de Janeiro', value: 'GIG'},
    {label: 'Istanbul', value: 'IST'},
    {label: 'Berlin', value: 'BER'},
  ];